baseURL = 'https://lilymara.xyz/'
languageCode = 'en-us'
title = "lily's thots"
theme = "archie"
copyright = "© Lily Mara"
enableRobotsTXT = true

[params]
customcss = [
    "css/pink.css",
    "css/toc.css",
    "css/callout.css",
    "css/copy.css",
    "css/reading-time.css",
    "css/img.css",
    "css/a.css",
    "css/heading.css",
    "css/open-heart.css",
    "css/homepage-box.css",
]
mode = "light"
favicon = "/favicon.png"

[permalinks]
    [permalinks.page]
        posts = '/posts/:year/:month/:slug/'

[[menu.main]]
name = "Buy my Book!"
url = "https://www.manning.com/books/refactoring-to-rust?utm_source=mara&utm_medium=affiliate&utm_campaign=book_mara_refactoring_1_6_21&a_aid=mara&a_bid=eedce54d"
weight = 5

[[menu.main]]
name = "/now"
url = "/now"
weight = 15

[markup.tableOfContents]
endLevel = 3
ordered = true
startLevel = 1

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser.attribute]
block = true

# Icons come from https://feathericons.com
[[params.social]]
name = "Youtube"
icon = "youtube"
url = "https://www.youtube.com/@lily-mara"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/pages/feeds/"

[[params.social]]
name = "Email"
icon = "at-sign"
url = "mailto:lily@lilymara.xyz"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/TheLily_Mara"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/lily-mara"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/lily-mara/"
